language: node_js
node_js:
  - "8"
script:
  - yarn test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
notifications:
  webhooks:
    urls:
      - https://hooks.glip.com/webhook/0fea074a-1b54-47ed-a7bc-5e741a0e2d75
    on_success: always
    on_failure: always
    on_start: always
